# Generated by Django 6.0.3 on 2026-03-05 14:02

from django.db import migrations

from django.conf import settings


def create_permission(apps, schema_editor):
    PermissionModel = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    content_type = ContentType.objects.get(app_label=app_label, model=model_name.lower())

    PermissionModel.objects.get_or_create(
        content_type=content_type,
        codename='can_set_unusable_password',
        defaults={"name": "Can set unusable passwords"},
    )

def remove_permission(apps, schema_editor):
    PermissionModel = apps.get_model('auth', 'Permission')

    PermissionModel.objects.filter(
        codename='can_set_unusable_password',
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(code=create_permission,reverse_code=remove_permission),
    ]
