"""
Django settings for Middleware project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^il6sec53p7l$!9--uqd0s_usqfs$&nr1m@s8n#8hlq7+3#6ja'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

ALLOWED_IPS = ['127.0.0.1']

MIDDLEWARE = [
    'Middleware.middlewares.SuspiciousActivityMiddleware',
    'Middleware.middlewares.IPWhitelistMiddleware',
    'Middleware.middlewares.TotalRequestsCounter',
    'Middleware.middlewares.RequestLoginMiddleware',
    'django.middleware.security.SecurityMiddleware', # add basic protection and headers
    'django.contrib.sessions.middleware.SessionMiddleware', #handles django session logic
    'Middleware.middlewares.SessionRateLimitingMiddleware',
    'django.middleware.common.CommonMiddleware', #redirect if slash at the end of url is missing
    'django.middleware.csrf.CsrfViewMiddleware', #enforces that we have crsf token on post request
    'django.contrib.auth.middleware.AuthenticationMiddleware', #attaches the django user to the request
    'django.contrib.messages.middleware.MessageMiddleware', #handles dj messages framework
    'django.middleware.clickjacking.XFrameOptionsMiddleware', #prevents dispalying our webside in iframe
]

ROOT_URLCONF = 'Middleware.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Middleware.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'middleware',
        'USER': 'tori',
        'PASSWORD': '123456',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

SUPPORTED_LANGUAGES ={
    'en': 'English',
    'de': 'German',
    'bg': 'Bulgarian',
}
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
REQUESTS_PER_MINUTE =5

SESSION_COOKIE_SECURE=True
SESSION_COOKIE_HTTPONLY=True